name: Build and Publish image to Docker hub
on:
  [workflow_dispatch]

jobs:
  publish-images:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v4
      - name: Build image
        run : docker build . pastedockerhubUsername/Imagename:tag
      - name: Push image to docker hub
        run : docker push dockerhubUsername/Imagename:tag
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}